server:
  port: 9000
spring:
  application:
    name: spring-cloud-openfeign
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: spring-cloud-openfeign:9000
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: zhang.springcloudservice.Entity
