server:
  port: 8761
eureka:
  instance:
    hostname: spring-cloud-main
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/