server:
  port: 8800
spring:
  application:
    name: spring-cloud-service02


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
